# Generated by Django 5.2.4 on 2025-08-01 05:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone_no', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_location', models.CharField(max_length=200)),
                ('user_DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Credential',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.user')),
                ('user_role', models.CharField(max_length=10)),
                ('user_password', models.TextField()),
            ],
        ),
    ]
