// App Constants
export const APP_NAME = 'Medi-AI';
export const APP_VERSION = '1.0.0';
export const APP_DESCRIPTION = 'Your AI-powered healthcare companion';

// Storage Keys
export const STORAGE_KEYS = {
  USER: 'medi-ai-user',
  LANGUAGE: 'medi-ai-language',
  THEME: 'medi-ai-theme',
  OFFLINE_MODE: 'medi-ai-offline-mode',
  UPLOAD_QUEUE: 'medi-ai-upload-queue',
  HISTORY: 'medi-ai-history',
  SETTINGS: 'medi-ai-settings',
};

// API Constants
export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    SIGNUP: '/auth/signup',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
  },
  SCANS: {
    UPLOAD: '/scans/upload',
    INTERPRET: '/scans/interpret',
    HISTORY: '/scans/history',
    DELETE: '/scans/delete',
  },
  MEDICINE: {
    SCAN: '/medicine/scan',
    SEARCH: '/medicine/search',
    INFO: '/medicine/info',
  },
  FACILITIES: {
    SEARCH: '/facilities/search',
    NEARBY: '/facilities/nearby',
    DETAILS: '/facilities/details',
  },
  SYMPTOMS: {
    CHAT: '/symptoms/chat',
    ASSESSMENT: '/symptoms/assessment',
    HISTORY: '/symptoms/history',
  },
  DOCTOR: {
    REQUESTS: '/doctor/requests',
    RESPOND: '/doctor/respond',
    PATIENTS: '/doctor/patients',
  },
};

// File Upload Constants
export const FILE_UPLOAD = {
  MAX_SIZE: 10 * 1024 * 1024, // 10MB
  ALLOWED_TYPES: {
    IMAGE: ['image/jpeg', 'image/png', 'image/webp'],
    PDF: ['application/pdf'],
    ALL: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
  },
  CHUNK_SIZE: 1024 * 1024, // 1MB chunks
};

// Medical Constants
export const MEDICAL_CONSTANTS = {
  CONFIDENCE_LEVELS: {
    HIGH: 85,
    MEDIUM: 60,
    LOW: 40,
  },
  RISK_LEVELS: {
    HIGH: 'high',
    MEDIUM: 'medium',
    LOW: 'low',
  },
  URGENCY_LEVELS: {
    EMERGENCY: 'emergency',
    HIGH: 'high',
    MEDIUM: 'medium',
    LOW: 'low',
  },
};

// UI Constants
export const UI_CONSTANTS = {
  ANIMATION_DURATION: 300,
  DEBOUNCE_DELAY: 500,
  TOAST_DURATION: 5000,
  MODAL_ANIMATION: 200,
  LOADING_DELAY: 200,
};

// Validation Constants
export const VALIDATION = {
  EMAIL_REGEX: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  PHONE_REGEX: /^[+]?[\d\s-()]{10,}$/,
  PASSWORD_MIN_LENGTH: 8,
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 50,
};

// Default Values
export const DEFAULTS = {
  LANGUAGE: 'en',
  THEME: 'light',
  OFFLINE_MODE: false,
  NOTIFICATIONS: true,
  AUTO_UPLOAD: true,
  SAVE_HISTORY: true,
};

// Error Messages
export const ERROR_MESSAGES = {
  NETWORK_ERROR: 'Network error. Please check your connection.',
  UNAUTHORIZED: 'You are not authorized to perform this action.',
  FILE_TOO_LARGE: 'File size exceeds the maximum limit.',
  INVALID_FILE_TYPE: 'Invalid file type. Please upload a valid file.',
  UPLOAD_FAILED: 'Upload failed. Please try again.',
  PROCESSING_FAILED: 'Processing failed. Please try again.',
  GENERIC_ERROR: 'Something went wrong. Please try again.',
};

// Success Messages
export const SUCCESS_MESSAGES = {
  LOGIN_SUCCESS: 'Login successful!',
  SIGNUP_SUCCESS: 'Account created successfully!',
  LOGOUT_SUCCESS: 'Logged out successfully!',
  UPLOAD_SUCCESS: 'File uploaded successfully!',
  SAVE_SUCCESS: 'Saved successfully!',
  DELETE_SUCCESS: 'Deleted successfully!',
  UPDATE_SUCCESS: 'Updated successfully!',
};

// Medical Disclaimers
export const MEDICAL_DISCLAIMERS = {
  AI_INTERPRETATION: 'This interpretation is generated by AI and should not replace professional medical advice. Always consult with a qualified healthcare provider for medical decisions.',
  SYMPTOM_CHECKER: 'This symptom checker is for informational purposes only and should not be used as a substitute for professional medical diagnosis, treatment, or advice.',
  MEDICINE_INFO: 'This medicine information is for educational purposes only. Always consult with a pharmacist or healthcare provider before taking any medication.',
  GENERAL: 'The information provided by Medi-AI is for educational and informational purposes only and should not be considered as medical advice.',
};
