export const languages = [
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
  },
  {
    code: 'ne',
    name: 'Nepali',
    nativeName: 'नेपाली',
  },
  {
    code: 'mai',
    name: 'Maithili',
    nativeName: 'मैथिली',
  },
  {
    code: 'bho',
    name: 'Bhojpuri',
    nativeName: 'भोजपुरी',
  },
  {
    code: 'ta',
    name: 'Tamang',
    nativeName: 'तामाङ',
  },
];

export const getLanguageByCode = (code) => {
  return languages.find(lang => lang.code === code) || languages[0];
};

export const getDefaultLanguage = () => 'en';

// Basic translations for common terms
export const translations = {
  en: {
    dashboard: 'Dashboard',
    scanInterpreter: 'Scan Interpreter',
    medicineScanner: 'Medicine Scanner',
    history: 'History',
    healthProviders: 'Health Providers',
    symptomChecker: 'Symptom Checker',
    appointments: 'Appointments',
    patientRequests: 'Patient Requests',
    profile: 'Profile',
    settings: 'Settings',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    doctor: 'Doctor',
    user: 'User',
    patient: 'Patient',
    welcome: 'Welcome',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    upload: 'Upload',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    close: 'Close',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    next: 'Next',
    previous: 'Previous',
    submit: 'Submit',
    confirm: 'Confirm',
  },
  ne: {
    dashboard: 'ड्यासबोर्ड',
    scanInterpreter: 'स्क्यान व्याख्याकर्ता',
    medicineScanner: 'औषधि स्क्यानर',
    history: 'इतिहास',
    healthProviders: 'स्वास्थ्य प्रदायकहरू',
    symptomChecker: 'लक्षण जाँचकर्ता',
    appointments: 'अपोइन्टमेन्टहरू',
    patientRequests: 'बिरामी अनुरोध',
    profile: 'प्रोफाइल',
    settings: 'सेटिङ्गहरू',
    login: 'लगइन',
    signup: 'साइन अप',
    logout: 'लगआउट',
    email: 'इमेल',
    password: 'पासवर्ड',
    name: 'नाम',
    doctor: 'डाक्टर',
    user: 'प्रयोगकर्ता',
    patient: 'बिरामी',
    welcome: 'स्वागतम्',
    loading: 'लोड हुँदै...',
    error: 'त्रुटि',
    success: 'सफल',
    upload: 'अपलोड',
    cancel: 'रद्द गर्नुहोस्',
    save: 'सुरक्षित गर्नुहोस्',
    delete: 'मेटाउनुहोस्',
    edit: 'सम्पादन गर्नुहोस्',
    view: 'हेर्नुहोस्',
    close: 'बन्द गर्नुहोस्',
    search: 'खोज्नुहोस्',
    filter: 'फिल्टर',
    sort: 'क्रम',
    next: 'अर्को',
    previous: 'अघिल्लो',
    submit: 'पेश गर्नुहोस्',
    confirm: 'पुष्टि गर्नुहोस्',
  },
  mai: {
    dashboard: 'ड्यासबोर्ड',
    scanInterpreter: 'स्क्यान व्याख्याकर्ता',
    medicineScanner: 'औषधि स्क्यानर',
    history: 'इतिहास',
    healthProviders: 'स्वास्थ्य प्रदायकहरू',
    symptomChecker: 'लक्षण परीक्षक',
    appointments: 'अपोइन्टमेन्टहरू',
    patientRequests: 'रोगी अनुरोध',
    profile: 'प्रोफाइल',
    settings: 'सेटिङ्गहरू',
    login: 'लगइन',
    signup: 'साइन अप',
    logout: 'लगआउट',
    email: 'इमेल',
    password: 'पासवर्ड',
    name: 'नाम',
    doctor: 'डाक्टर',
    user: 'प्रयोगकर्ता',
    patient: 'रोगी',
    welcome: 'स्वागतम्',
    loading: 'लोड हुँदै...',
    error: 'त्रुटि',
    success: 'सफल',
    upload: 'अपलोड',
    cancel: 'रद्द',
    save: 'सुरक्षित',
    delete: 'मेटाउ',
    edit: 'सम्पादन',
    view: 'हेर',
    close: 'बन्द',
    search: 'खोज',
    filter: 'फिल्टर',
    sort: 'क्रम',
    next: 'अर्को',
    previous: 'अघिल्लो',
    submit: 'पेश',
    confirm: 'पुष्टि',
  },
  bho: {
    dashboard: 'ड्यासबोर्ड',
    scanInterpreter: 'स्क्यान व्याख्याकर्ता',
    medicineScanner: 'दवाई स्क्यानर',
    history: 'इतिहास',
    healthProviders: 'स्वास्थ्य प्रदायकहरू',
    symptomChecker: 'लक्षण जाँचकर्ता',
    appointments: 'अपोइन्टमेन्टहरू',
    patientRequests: 'मरीज के अनुरोध',
    profile: 'प्रोफाइल',
    settings: 'सेटिङ्गहरू',
    login: 'लगइन',
    signup: 'साइन अप',
    logout: 'लगआउट',
    email: 'इमेल',
    password: 'पासवर्ड',
    name: 'नाम',
    doctor: 'डाक्टर',
    user: 'प्रयोगकर्ता',
    patient: 'मरीज',
    welcome: 'स्वागतम्',
    loading: 'लोड हो रहल बा...',
    error: 'त्रुटि',
    success: 'सफल',
    upload: 'अपलोड',
    cancel: 'रद्द',
    save: 'सुरक्षित',
    delete: 'मेटाउ',
    edit: 'सम्पादन',
    view: 'देख',
    close: 'बन्द',
    search: 'खोज',
    filter: 'फिल्टर',
    sort: 'क्रम',
    next: 'अगला',
    previous: 'पहिला',
    submit: 'पेश',
    confirm: 'पुष्टि',
  },
  ta: {
    dashboard: 'ड्यासबोर्ड',
    scanInterpreter: 'स्क्यान व्याख्याकर्ता',
    medicineScanner: 'औषधि स्क्यानर',
    history: 'इतिहास',
    healthProviders: 'स्वास्थ्य प्रदायकहरू',
    symptomChecker: 'लक्षण जाँचकर्ता',
    appointments: 'अपोइन्टमेन्टहरू',
    patientRequests: 'बिरामी अनुरोध',
    profile: 'प्रोफाइल',
    settings: 'सेटिङ्गहरू',
    login: 'लगइन',
    signup: 'साइन अप',
    logout: 'लगआउट',
    email: 'इमेल',
    password: 'पासवर्ड',
    name: 'नाम',
    doctor: 'डाक्टर',
    user: 'प्रयोगकर्ता',
    patient: 'बिरामी',
    welcome: 'स्वागतम्',
    loading: 'लोड हुँदै...',
    error: 'त्रुटि',
    success: 'सफल',
    upload: 'अपलोड',
    cancel: 'रद्द',
    save: 'सुरक्षित',
    delete: 'मेटाउ',
    edit: 'सम्पादन',
    view: 'हेर',
    close: 'बन्द',
    search: 'खोज',
    filter: 'फिल्टर',
    sort: 'क्रम',
    next: 'अर्को',
    previous: 'अघिल्लो',
    submit: 'पेश',
    confirm: 'पुष्टि',
  },
};

export const t = (key, language = 'en') => {
  return translations[language]?.[key] || translations.en[key] || key;
};
